In [1]:
import numpy as np

def analyze_array(arr):
    try:
        # Step 1: Reshape the array to a 2D array with 5 rows
        reshaped_array = arr.reshape(5, -1)

        # Step 2: Calculate the sum of each column
        column_sums = reshaped_array.sum(axis=0)

        # Step 3: Find the index of the column with the maximum sum
        max_col_index = np.argmax(column_sums)

        # Step 4: Get the maximum column sum
        max_col_sum = column_sums[max_col_index]

        return reshaped_array, max_col_index, max_col_sum
    except ValueError:
        return "Array cannot be reshaped into 5 rows."

# Example Usage
arr = np.random.randint(1, 51, size=20)  # Generating a random 1D array with 20 elements
reshaped_array, max_col_index, max_col_sum = analyze_array(arr)

print("Original Array:")
print(arr)
print("\nReshaped Array (5 rows):")
print(reshaped_array)
print(f"\nColumn with Maximum Sum: {max_col_index}")
print(f"Maximum Column Sum: {max_col_sum}")


Original Array:
[19  9 50  3 36 24  7 21  7 13 12 29 20 28 22 48 26 40 11 45]

Reshaped Array (5 rows):
[[19  9 50  3]
 [36 24  7 21]
 [ 7 13 12 29]
 [20 28 22 48]
 [26 40 11 45]]

Column with Maximum Sum: 3
Maximum Column Sum: 146
