In [1]:
import numpy as np

# Create indices for i and j
i = np.arange(5).reshape(-1, 1)  # Column vector
j = np.arange(5).reshape(1, -1)  # Row vector

# Compute A[i, j] = i^2 + j^2
A = i**2 + j**2

print("Generated Array:")
print(A)


Generated Array:
[[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]
 [16 17 20 25 32]]
